# Generated by Django 3.0.7 on 2020-09-28 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.Profile'),
        ),
    ]
